#!/bin/bash 
#####################################################################
#                                                                   #
#               Update cue manager                               #
#               (c) Allen, 2017                                    #
#                                                                   #
#####################################################################

# exit if a command fails
set -e

# global option variables
LOG="/dev/stdout"

#########################################
#PHASE 1 : collects file name from the command line
#########################################

while [ $1 ]
do
    p=$1

    if [ $p = "-help" ] || [ $p = "-h" ]; then
        echo "===================================="
        echo "Modify your cueNum.txt and cueTips.txt"        
        echo "Use './updateCue XXX' to updateCue manager"
		echo "====================================" 
        exit
    elif [ ${p:0:1} != "-" ]; then
		FILES="$p"
    else
    	echo "===================================="
        echo "Modify your cueNum.txt and cueTips.txt"        
        echo "Use './updateCue XXX' to updateCue manager"
		echo "====================================" 
        exit
    fi
            
    
shift
done

if [ -z $FILES ]; then
	echo "====================================" 
    echo "Please, provide app's name to compile"
    echo "====================================" 
    exit
fi


#########################################
#PHASE 2 : compile file
#########################################


for p in $FILES; do
	S=$(dirname "$p")      #CURRENT FOLDER
	F=$(basename "$p")
	P=${F%.dsp}             #APP NAME
  
	T="faustSmartphone.$P"
	
   
		echo "Wait...." 
			
		cp $S/cueNums.txt $T/iOS > $LOG
		cp $S/cueTips.txt $T/iOS > $LOG
		
		echo "====================================" 
		echo "Cue and Tips are UPDATED"
		echo "====================================" 
	 

done


