/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.DspFaustMotion;

public class dsp_faust_motionJNI {

  static {
    try {
        java.lang.System.loadLibrary("dsp_faust_motion");
    } catch (UnsatisfiedLinkError e) {
        java.lang.System.err.println("native code library failed to load.\n" + e);
        java.lang.System.exit(1);
    }
  }

  public final static native long new_DspFaustMotion(int jarg1, int jarg2);
  public final static native void delete_DspFaustMotion(long jarg1);
  public final static native boolean DspFaustMotion_start(long jarg1, DspFaustMotion jarg1_);
  public final static native void DspFaustMotion_stop(long jarg1, DspFaustMotion jarg1_);
  public final static native void DspFaustMotion_render(long jarg1, DspFaustMotion jarg1_);
  public final static native boolean DspFaustMotion_isRunning(long jarg1, DspFaustMotion jarg1_);
  public final static native String DspFaustMotion_getJSONUI(long jarg1, DspFaustMotion jarg1_);
  public final static native String DspFaustMotion_getJSONMeta(long jarg1, DspFaustMotion jarg1_);
  public final static native int DspFaustMotion_getParamsCount(long jarg1, DspFaustMotion jarg1_);
  public final static native void DspFaustMotion_setParamValue__SWIG_0(long jarg1, DspFaustMotion jarg1_, String jarg2, float jarg3);
  public final static native void DspFaustMotion_setParamValue__SWIG_1(long jarg1, DspFaustMotion jarg1_, int jarg2, float jarg3);
  public final static native float DspFaustMotion_getParamValue__SWIG_0(long jarg1, DspFaustMotion jarg1_, String jarg2);
  public final static native float DspFaustMotion_getParamValue__SWIG_1(long jarg1, DspFaustMotion jarg1_, int jarg2);
  public final static native String DspFaustMotion_getParamAddress(long jarg1, DspFaustMotion jarg1_, int jarg2);
  public final static native float DspFaustMotion_getParamMin__SWIG_0(long jarg1, DspFaustMotion jarg1_, String jarg2);
  public final static native float DspFaustMotion_getParamMin__SWIG_1(long jarg1, DspFaustMotion jarg1_, int jarg2);
  public final static native float DspFaustMotion_getParamMax__SWIG_0(long jarg1, DspFaustMotion jarg1_, String jarg2);
  public final static native float DspFaustMotion_getParamMax__SWIG_1(long jarg1, DspFaustMotion jarg1_, int jarg2);
  public final static native float DspFaustMotion_getParamInit__SWIG_0(long jarg1, DspFaustMotion jarg1_, String jarg2);
  public final static native float DspFaustMotion_getParamInit__SWIG_1(long jarg1, DspFaustMotion jarg1_, int jarg2);
  public final static native String DspFaustMotion_getParamTooltip__SWIG_0(long jarg1, DspFaustMotion jarg1_, String jarg2);
  public final static native String DspFaustMotion_getParamTooltip__SWIG_1(long jarg1, DspFaustMotion jarg1_, int jarg2);
  public final static native void DspFaustMotion_propagateAcc(long jarg1, DspFaustMotion jarg1_, int jarg2, float jarg3);
  public final static native void DspFaustMotion_setAccConverter(long jarg1, DspFaustMotion jarg1_, int jarg2, int jarg3, int jarg4, float jarg5, float jarg6, float jarg7);
  public final static native void DspFaustMotion_propagateGyr(long jarg1, DspFaustMotion jarg1_, int jarg2, float jarg3);
  public final static native void DspFaustMotion_setGyrConverter(long jarg1, DspFaustMotion jarg1_, int jarg2, int jarg3, int jarg4, float jarg5, float jarg6, float jarg7);
  public final static native float DspFaustMotion_getCPULoad(long jarg1, DspFaustMotion jarg1_);
  public final static native int DspFaustMotion_getScreenColor(long jarg1, DspFaustMotion jarg1_);
}
