/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.DspFaust;

public class dsp_faustJNI {

  static {
    try {
        java.lang.System.loadLibrary("dsp_faust");
    } catch (UnsatisfiedLinkError e) {
        java.lang.System.err.println("native code library failed to load.\n" + e);
        java.lang.System.exit(1);
    }
  }

  public final static native long new_DspFaust(int jarg1, int jarg2);
  public final static native void delete_DspFaust(long jarg1);
  public final static native boolean DspFaust_start(long jarg1, DspFaust jarg1_);
  public final static native void DspFaust_stop(long jarg1, DspFaust jarg1_);
  public final static native void DspFaust_render(long jarg1, DspFaust jarg1_);
  public final static native void DspFaust_setInput(long jarg1, DspFaust jarg1_, int jarg2, float jarg3);
  public final static native float DspFaust_getOutput(long jarg1, DspFaust jarg1_, int jarg2);
  public final static native int DspFaust_getOutputChannelNum(long jarg1, DspFaust jarg1_);
  public final static native int DspFaust_getInputChannelNum(long jarg1, DspFaust jarg1_);
  public final static native boolean DspFaust_isRunning(long jarg1, DspFaust jarg1_);
  public final static native String DspFaust_getJSONUI(long jarg1, DspFaust jarg1_);
  public final static native String DspFaust_getJSONMeta(long jarg1, DspFaust jarg1_);
  public final static native int DspFaust_getParamsCount(long jarg1, DspFaust jarg1_);
  public final static native void DspFaust_setParamValue__SWIG_0(long jarg1, DspFaust jarg1_, String jarg2, float jarg3);
  public final static native void DspFaust_setParamValue__SWIG_1(long jarg1, DspFaust jarg1_, int jarg2, float jarg3);
  public final static native float DspFaust_getParamValue__SWIG_0(long jarg1, DspFaust jarg1_, String jarg2);
  public final static native float DspFaust_getParamValue__SWIG_1(long jarg1, DspFaust jarg1_, int jarg2);
  public final static native String DspFaust_getParamAddress(long jarg1, DspFaust jarg1_, int jarg2);
  public final static native float DspFaust_getParamMin__SWIG_0(long jarg1, DspFaust jarg1_, String jarg2);
  public final static native float DspFaust_getParamMin__SWIG_1(long jarg1, DspFaust jarg1_, int jarg2);
  public final static native float DspFaust_getParamMax__SWIG_0(long jarg1, DspFaust jarg1_, String jarg2);
  public final static native float DspFaust_getParamMax__SWIG_1(long jarg1, DspFaust jarg1_, int jarg2);
  public final static native float DspFaust_getParamInit__SWIG_0(long jarg1, DspFaust jarg1_, String jarg2);
  public final static native float DspFaust_getParamInit__SWIG_1(long jarg1, DspFaust jarg1_, int jarg2);
  public final static native String DspFaust_getParamTooltip__SWIG_0(long jarg1, DspFaust jarg1_, String jarg2);
  public final static native String DspFaust_getParamTooltip__SWIG_1(long jarg1, DspFaust jarg1_, int jarg2);
  public final static native void DspFaust_propagateAcc(long jarg1, DspFaust jarg1_, int jarg2, float jarg3);
  public final static native void DspFaust_setAccConverter(long jarg1, DspFaust jarg1_, int jarg2, int jarg3, int jarg4, float jarg5, float jarg6, float jarg7);
  public final static native void DspFaust_propagateGyr(long jarg1, DspFaust jarg1_, int jarg2, float jarg3);
  public final static native void DspFaust_setGyrConverter(long jarg1, DspFaust jarg1_, int jarg2, int jarg3, int jarg4, float jarg5, float jarg6, float jarg7);
  public final static native float DspFaust_getCPULoad(long jarg1, DspFaust jarg1_);
  public final static native int DspFaust_getScreenColor(long jarg1, DspFaust jarg1_);
}
